export const GET_CHARACTER_EVENT = 'GET_CHARACTER_EVENT';
export const GOT_CHARACTER_EVENT = 'GOT_CHARACTER_EVENT';
export const GET_CHARACTER_EVENT_ERROR = 'GET_CHARACTER_EVENT_ERROR';

export const SEND_SEARCH_TERM = 'SEND_SEARCH_TERM';
export const SENT_SEARCH_TERM = 'SENT_SEARCH_TERM';
export const SEND_SEARCH_TERM_ERROR = 'SEND_SEARCH_TERM_ERROR';
